name: Automated Workflow for Glacier dataset

on:
  # Schedule to run on the 1st day of each month
  schedule:
    - cron: '0 0 1 * *'

  # Run on push to master branch
  push:
    branches:
      - main

  # Run on pull requests targeting the master branch
  pull_request:
    branches:
      - main

  # Allows manual triggering of the workflow
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    # Conditional job trigger based on the branch being present
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Run Makefile
      run: |
        source venv/bin/activate
        cd scripts
        make 
      
    - name: Push and Commit      
      env:
        CI_COMMIT_NAME: "Automated commit"
        CI_COMMIT_EMAIL: "actions@users.noreply.github.com"
        CI_COMMIT_MESSAGE: "Automated commit"
      run: |
        git config --global user.email "${{env.CI_COMMIT_EMAIL}}"
        git config --global user.name "${{env.CI_COMMIT_NAME}}"
        git diff --quiet && echo "No changes to commit" || (git add . && git commit -m "${{env.CI_COMMIT_MESSAGE}}" && git push)